services:
  openclaw:
    build: .
    container_name: eddyclawd
    restart: always
    ports:
      - "18789:18789"
    volumes:
      - ./src/skills:/home/node/.openclaw/workspace/skills
      - openclaw_data:/home/node/.openclaw
    environment:
      - NODE_ENV=production
      - OPENCLAW_PORT=18789

volumes:
  openclaw_data:
